### ISSUE TITLE
More detailed code

### ISSUE THREAD

**Issue by mazeyang** [MichaelZhouwang/Sequence_Span_Rewriting#1]
Hello,

Thank you for such amazing work. The idea of rewrite is very inspiring for our work. We would like to learn more about the implementation of the algorithm. When will more detailed code be released? Thank you very much!

**Comment by MichaelZhouwang** [comment]
> Hello,
> 
> Thank you for such amazing work. The idea of rewrite is very inspiring for our work. We would like to learn more about the implementation of the algorithm. When will more detailed code be released? Thank you very much!

Hi, we have uploaded the data generation scripts and training scripts. Feel free to contact me if you have any issues.
