### ISSUE TITLE
Could you please provide more detailed instructions?

### ISSUE THREAD

**Issue by shadowkiller33** [MichaelZhouwang/Sequence_Span_Rewriting#3]
Hi! It's a wonderful work and thanks for your sharing. Could you please proveide more detailed code instructions like training settings? Besides, I'm little confused about the running order, should we run data_gen.py and then run run_summarization.py?

Can't be more appreciated for your reply.

**Comment by MichaelZhouwang** [comment]
Hi, thanks a lot for your interest! Yes you need to first run data_gen.py to generate data used for SSR training. And then run_summarization.py (this originally named by huggingface, and should actually be named run_seq2seq.py, and we use it for SSR training) with the generated data to train the model. For the training hyperparameters, please refer to the paper.

Feel free to contact if you have any further questions!

**Comment by 1754699523** [comment]
> Hi! It's a wonderful work and thanks for your sharing. Could you please proveide more detailed code instructions like training settings? Besides, I'm little confused about the running order, should we run data_gen.py and then run run_summarization.py?
> 
> Can't be more appreciated for your reply.

hi,do you have datasets
