### ISSUE TITLE
Need ssr-small & ssr-large pre-trained checkpoint!

### ISSUE THREAD

**Issue by Lyshc-cgc** [MichaelZhouwang/Sequence_Span_Rewriting#4]
As described in title, could you please provide ssr-small and ssr-large pre-trained checkpoint? I think we can compare models or do other downstream tasks with the same ‘**size**' conveniently if we have checkpoints for diffrent size model

**Comment by Lyshc-cgc** [comment]
@MichaelZhouwang  I will appreciate it if you can handle the issue! 感激不尽

**Comment by MichaelZhouwang** [comment]
@Lyshc-cgc sorry for the late response! We could not release the small and large checkpoints because I've already left Microsoft Research. Sorry for the inconvenience.
